# Generated by Django 5.0.6 on 2024-06-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sunday', models.CharField(max_length=100, default="closed")),
                ('monday', models.CharField(max_length=100, default="closed")),
                ('tuesday', models.CharField(max_length=100, default="closed")),
                ('wednesday', models.CharField(max_length=100, default="closed")),
                ('thursday', models.CharField(max_length=100, default="closed")),
                ('friday', models.CharField(max_length=100, default="closed")),
                ('saturday', models.CharField(max_length=100, default="closed")),
            ],
        ),
    ]
